name: Deploy to Dreamhost

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dreamhost
    steps:
      - uses: actions/checkout@master
      - name: Secure Copy
        uses: nogsantos/ssh-scp-deploy@v1.3.0
        with:
          src: ./docs/*
          host: ${{ vars.SSH_HOST }}
          remote: ${{ vars.SSH_DIR }}
          port: ${{ vars.SSH_PORT }}
          user: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
