name: Deploy to Dreamhost

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to Dreamhost
    steps:
      - name: Secure copy
        env:
          src: ./docs/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: 22
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
        run: |
          echo "$host"
          ls
          
